# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Blake Sirius Anacleto
# Description of the Site
description: Home of a Software Engineer
# URL of Image of the Site
site-image: /assets/images/hero_image.jpg
# Keywords of the Site
site-keywords: Site, Portfolio
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/hero_image.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mythology06@gmail.com
phone_number: 8801334182900
facebook_username: SoftwareEngineerBlake
twitter_username: TheSiriusSystem
github_username: TheSiriusSystem

# Google Analytics
google-analytics: UA-10064755186-1

# Author Main Details
author-name: Blake Sirius Anacleto
author-role: Software Engineer & Graphic Designer
author-tagline: Creating Designs That Stand Out.
# URL for the Image of the Author
author-image: /assets/images/avatar.jpg
# 60 Words About the Author
author-about: Hello! I am <del>Roopkotha</del> Blake, a software engineer and aspiring graphic designer. While my main passion lies within programming, I can also deliver stunning visuals. I specialize in building games and crafting bold, flashy but functional designs. Being mainly self-taught, I have been interested in development since childhood. In my spare time, I tend to game a lot.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/TheSiriusSystem

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
